# Generated by Django 5.0.3 on 2025-06-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0005_customerreview_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='career',
            name='job_title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='career',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='banner_title',
            field=models.CharField(default='Our Offers', max_length=25),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='our_works',
            name='title',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='our_works',
            name='work_category',
            field=models.CharField(max_length=25),
        ),
    ]
