# Generated by Django 5.0.3 on 2025-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0006_solarpanel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invertor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
    ]
