# Generated by Django 5.0.3 on 2025-04-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0007_invertor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
