# Generated by Django 5.0.3 on 2025-04-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0008_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_brands', models.CharField(max_length=30)),
                ('invertor_brands', models.CharField(max_length=30)),
                ('total_power', models.CharField(blank=True, max_length=30)),
                ('packages', models.TextField()),
            ],
        ),
    ]
