# Generated by Django 5.0.3 on 2025-04-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0010_brand_product_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brands',
        ),
        migrations.RemoveField(
            model_name='package',
            name='products',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
