# Generated by Django 5.0.3 on 2025-04-24 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0012_package_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
