# Generated by Django 5.0.3 on 2025-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0013_delete_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
