# Generated by Django 5.0.3 on 2025-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0014_invoice_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
