# Generated by Django 5.0.3 on 2025-04-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0015_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
