# Generated by Django 5.0.3 on 2025-06-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0007_alter_login_password_alter_login_username'),
        ('genrapp', '0016_alter_package_price'),
    ]

    operations = [
    ]
