# Generated by Django 5.0.3 on 2025-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0017_merge_20250612_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerreview',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customerreview',
            name='full_name',
            field=models.CharField(max_length=25),
        ),
    ]
