# Generated by Django 5.0.3 on 2025-06-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0018_alter_customerreview_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
