# Generated by Django 5.0.3 on 2025-06-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genrapp', '0019_alter_gallery_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
